services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=voteoff
      - POSTGRES_PASSWORD=voteoff
      - POSTGRES_DB=voteoff
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
volumes:
  db_data: