# Generated by Django 5.2.6 on 2025-09-30 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField()),
                ('choices', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(null=True)),
                ('electoral_system', models.CharField(choices=[('RC', 'Ranked Choice'), ('PL', 'Plurality')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('voter_name', models.CharField()),
                ('vote', models.JSONField(null=True)),
                ('submitted', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voter_name', 'event'), name='unique_voter_names_in_event')],
            },
        ),
    ]
