# Generated by Django 5.2.7 on 2025-10-27 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_ballot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
