# Generated by Django 5.2.7 on 2025-10-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_ballot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='electoral_system',
            field=models.CharField(max_length=2),
        ),
    ]
