# Generated by Django 5.2.7 on 2026-01-21 05:18

from django.db import migrations, models


def set_default_status(apps, schema_editor):
    Event = apps.get_model("vote", "Event")
    for event in Event.objects.all():
        if event.closed:
            event.status = "CL"
        else:
            event.status = "RE"
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0005_event_show_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("RE", "Registring"), ("VO", "Voting"), ("CL", "Closed")],
                default="RE",
                max_length=2,
            ),
        ),
        migrations.RunPython(
            set_default_status, reverse_code=migrations.RunPython.noop
        ),
    ]
