# Generated by Django 5.2.7 on 2026-01-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('RE', 'Registering'), ('VO', 'Voting'), ('CL', 'Closed')], default='RE', max_length=2),
        ),
    ]
