# Generated by Django 5.2.7 on 2026-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_voting',
            field=models.BooleanField(default=False),
        ),
    ]
