# Generated by Django 5.2.7 on 2026-05-18 04:34

from django.db import migrations


def split_event_status(apps, schema_editor):
    Event = apps.get_model("vote", "Event")
    for event in Event.objects.all():
        if event.status == "RE":
            event.allow_registration = True
            event.allow_voting = False
        elif event.status == "VO":
            event.allow_registration = False
            event.allow_voting = True
        elif event.status == "CL":
            event.allow_registration = False
            event.allow_voting = False
        else:
            raise ValueError(f"Unknown status: {event.status}")
        event.save()


def reverse_split_event_status(apps, schema_editor):
    Event = apps.get_model("vote", "Event")
    for event in Event.objects.all():
        if event.allow_registration and not event.allow_voting:
            event.status = "RE"
        elif not event.allow_registration and event.allow_voting:
            event.status = "VO"
        elif not event.allow_registration and not event.allow_voting:
            event.status = "CL"
        else:
            raise ValueError(
                f"Invalid combination of permissions: {event.allow_registration}, {event.allow_voting}"
            )
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0008_event_allow_registration_event_allow_voting"),
    ]

    operations = [
        migrations.RunPython(
            split_event_status, reverse_code=reverse_split_event_status
        )
    ]
