# Generated by Django 5.2.7 on 2026-05-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_migrate_event_status_to_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
