# Generated by Django 5.2.7 on 2026-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_remove_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_registration',
            field=models.BooleanField(default=False),
        ),
    ]
